GET http://localhost:3000/places.json

### post create place
POST http://localhost:3000/places.json
Content-Type: application/json

{
  "name": "Golden Gate Bridge",
  "address": "San Francisco, CA",
  "image_url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ4fYtNnFbnIKDT_5ZMSHAD2ZQK3ZwPK5swZw&usqp=CAU"
}

### GET places Show
GET http://localhost:3000/places/22

### Patch places update
PATCH http://localhost:3000/places/9.json
Content-Type: application/json

{
  "name": "new_name",
  "address": "123",
  "image_url": "pic"
}